name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Install dependencies
      run: cd build_XX && make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
