name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Create Directory
      run: mkdir build

    - name: Install dependencies
      run: ls -la
