name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Install Qt aditional
      run: sudo apt install qt5-qmake qt5-default qtscript5-dev

    - name: Install dependencies
      run: cd build_XX && qmake

    - name: Build
      run: make